-- Q1.1
SELECT sum(LO_EXTENDEDPRICE * LO_DISCOUNT) AS revenue
FROM lineorder
WHERE
  LO_ORDERDATE >= DATE '1993-01-01' AND
  LO_ORDERDATE <= DATE '1993-12-31' AND
  LO_DISCOUNT >= 1 AND LO_DISCOUNT <= 3 AND
  LO_QUANTITY < 25;
 
-- Q1.2
SELECT sum(LO_EXTENDEDPRICE * LO_DISCOUNT) AS revenue
FROM lineorder
WHERE
  LO_ORDERDATE >= DATE '1994-01-01' AND
  LO_ORDERDATE < DATE '1994-02-01' AND
  LO_DISCOUNT BETWEEN 4 AND 6 AND
  LO_QUANTITY BETWEEN 26 AND 35;
 
-- Q1.3
SELECT sum(LO_EXTENDEDPRICE * LO_DISCOUNT) AS revenue
FROM lineorder
WHERE
  LO_ORDERDATE >= DATE '1994-02-07' AND
  LO_ORDERDATE <= DATE '1994-02-13' AND
  LO_DISCOUNT BETWEEN 5 AND 7 AND
  LO_QUANTITY BETWEEN 26 AND 35;
 
-- Q2.1
SELECT sum(LO_REVENUE), EXTRACT(YEAR FROM LO_ORDERDATE), P_BRAND
FROM
  lineorder JOIN
  (SELECT P_BRAND, P_PARTKEY FROM part WHERE P_CATEGORY = 'MFGR#12') as part ON LO_PARTKEY = P_PARTKEY JOIN
  (SELECT S_REGION, S_SUPPKEY FROM supplier WHERE S_REGION = 'AMERICA') as supplier ON LO_SUPPKEY = S_SUPPKEY
GROUP BY EXTRACT(YEAR FROM LO_ORDERDATE), P_BRAND
ORDER BY EXTRACT(YEAR FROM LO_ORDERDATE), P_BRAND;
 
-- Q2.2
SELECT sum(LO_REVENUE), EXTRACT(YEAR FROM LO_ORDERDATE), P_BRAND
FROM
  lineorder JOIN
  (SELECT P_PARTKEY, P_BRAND FROM part WHERE P_BRAND >= 'MFGR#2221' AND P_BRAND <= 'MFGR#2228') as part ON LO_PARTKEY = P_PARTKEY JOIN
  (SELECT S_SUPPKEY FROM supplier WHERE S_REGION = 'ASIA') as supplier ON LO_SUPPKEY = S_SUPPKEY
GROUP BY EXTRACT(YEAR FROM LO_ORDERDATE), P_BRAND
ORDER BY EXTRACT(YEAR FROM LO_ORDERDATE), P_BRAND;
 
-- Q2.3
SELECT sum(LO_REVENUE), EXTRACT(YEAR FROM LO_ORDERDATE), P_BRAND
FROM
  lineorder JOIN
  (SELECT P_PARTKEY, P_BRAND FROM part WHERE P_BRAND = 'MFGR#2239') as part ON LO_PARTKEY = P_PARTKEY JOIN
  (SELECT S_SUPPKEY FROM supplier WHERE S_REGION = 'EUROPE') as supplier ON LO_SUPPKEY = S_SUPPKEY
GROUP BY EXTRACT(YEAR FROM LO_ORDERDATE), P_BRAND
ORDER BY EXTRACT(YEAR FROM LO_ORDERDATE), P_BRAND;
 
-- Q3.1
SELECT C_NATION, S_NATION, EXTRACT(YEAR FROM LO_ORDERDATE), sum(LO_REVENUE) AS revenue
FROM
  (SELECT LO_ORDERDATE, LO_CUSTKEY, LO_SUPPKEY, LO_REVENUE FROM lineorder
  WHERE LO_ORDERDATE >= DATE '1992-01-01' AND LO_ORDERDATE < DATE '1998-01-01') as lineorder JOIN
  (SELECT C_CUSTKEY, C_NATION FROM customer WHERE C_REGION = 'ASIA') as customer ON LO_CUSTKEY = C_CUSTKEY JOIN
  (SELECT S_SUPPKEY, S_NATION FROM supplier WHERE S_REGION = 'ASIA') as supplier ON LO_SUPPKEY = S_SUPPKEY
GROUP BY C_NATION, S_NATION, EXTRACT(YEAR FROM LO_ORDERDATE)
ORDER BY EXTRACT(YEAR FROM LO_ORDERDATE) ASC, sum(LO_REVENUE);
 
-- Q3.2
SELECT C_CITY, S_CITY, EXTRACT(YEAR FROM LO_ORDERDATE), sum(LO_REVENUE) AS revenue
FROM
  (SELECT LO_ORDERDATE, LO_REVENUE, LO_CUSTKEY, LO_SUPPKEY FROM lineorder
   WHERE LO_ORDERDATE >= DATE '1992-01-01' AND LO_ORDERDATE < DATE '1998-01-01') as lineorder JOIN
  (SELECT C_CUSTKEY, C_CITY FROM customer WHERE C_NATION = 'UNITED STATES') as customer ON LO_CUSTKEY = C_CUSTKEY JOIN
  (SELECT S_SUPPKEY, S_CITY FROM supplier WHERE S_NATION = 'UNITED STATES') as supplier ON LO_SUPPKEY = S_SUPPKEY
GROUP BY C_CITY, S_CITY, EXTRACT(YEAR FROM LO_ORDERDATE)
ORDER BY EXTRACT(YEAR FROM LO_ORDERDATE) ASC, sum(LO_REVENUE) DESC;
 
-- Q3.3
SELECT C_CITY, S_CITY, EXTRACT(YEAR FROM LO_ORDERDATE), sum(LO_REVENUE) AS revenue
FROM
  (SELECT LO_ORDERDATE, LO_REVENUE, LO_CUSTKEY, LO_SUPPKEY FROM lineorder
   WHERE LO_ORDERDATE >= DATE '1992-01-01' AND LO_ORDERDATE < DATE '1998-01-01') as lineorder JOIN
  (SELECT C_CUSTKEY, C_CITY FROM customer WHERE C_CITY = 'UNITED KI1' OR C_CITY = 'UNITED KI5') as customer ON LO_CUSTKEY = C_CUSTKEY JOIN
  (SELECT S_SUPPKEY, S_CITY FROM supplier WHERE S_CITY = 'UNITED KI1' OR S_CITY = 'UNITED KI5') as supplier ON LO_SUPPKEY = S_SUPPKEY
GROUP BY C_CITY, S_CITY, EXTRACT(YEAR FROM LO_ORDERDATE)
ORDER BY EXTRACT(YEAR FROM LO_ORDERDATE) ASC, sum(LO_REVENUE) DESC;
 
-- Q3.4
SELECT C_CITY, S_CITY, EXTRACT(YEAR FROM LO_ORDERDATE), sum(LO_REVENUE) AS revenue
FROM
  (SELECT LO_ORDERDATE, LO_REVENUE, LO_CUSTKEY, LO_SUPPKEY FROM lineorder
   WHERE LO_ORDERDATE >= DATE '1997-12-01' AND LO_ORDERDATE <= DATE '1997-12-31') as lineorder JOIN
  (SELECT C_CUSTKEY, C_CITY FROM customer WHERE C_CITY = 'UNITED KI1' OR C_CITY = 'UNITED KI5') as customer ON LO_CUSTKEY = C_CUSTKEY JOIN
  (SELECT S_SUPPKEY, S_CITY FROM supplier WHERE S_CITY = 'UNITED KI1' OR S_CITY = 'UNITED KI5') as supplier ON LO_SUPPKEY = S_SUPPKEY
GROUP BY C_CITY, S_CITY, EXTRACT(YEAR FROM LO_ORDERDATE)
ORDER BY EXTRACT(YEAR FROM LO_ORDERDATE) ASC, sum(LO_REVENUE) DESC;
 
-- Q4.1
SELECT EXTRACT(YEAR FROM LO_ORDERDATE), C_NATION, sum(LO_REVENUE - LO_SUPPLYCOST) AS profit
FROM
  lineorder JOIN
  (SELECT P_PARTKEY FROM part WHERE P_MFGR = 'MFGR#1' OR P_MFGR = 'MFGR#2') as part ON LO_PARTKEY = P_PARTKEY JOIN
  (SELECT S_SUPPKEY FROM supplier WHERE S_REGION = 'AMERICA') ON LO_SUPPKEY = S_SUPPKEY JOIN
  (SELECT C_CUSTKEY, C_NATION FROM customer WHERE C_REGION = 'AMERICA') as customer ON LO_CUSTKEY = C_CUSTKEY
GROUP BY EXTRACT(YEAR FROM LO_ORDERDATE), C_NATION
ORDER BY EXTRACT(YEAR FROM LO_ORDERDATE) ASC, C_NATION ASC;
 
-- Q4.2
SELECT EXTRACT(YEAR FROM LO_ORDERDATE), S_NATION, P_CATEGORY, sum(LO_REVENUE - LO_SUPPLYCOST) AS profit
FROM
  (SELECT LO_ORDERDATE, LO_REVENUE, LO_CUSTKEY, LO_SUPPKEY, LO_PARTKEY, LO_SUPPLYCOST FROM lineorder
   WHERE LO_ORDERDATE >= DATE '1997-01-01' AND LO_ORDERDATE < DATE '1999-01-01') as lineorder JOIN
  (SELECT P_PARTKEY, P_CATEGORY FROM part WHERE P_MFGR = 'MFGR#1' OR P_MFGR = 'MFGR#2') as part ON LO_PARTKEY = P_PARTKEY JOIN
  (SELECT S_SUPPKEY, S_REGION, S_NATION FROM supplier WHERE S_REGION = 'AMERICA') as supplier ON LO_SUPPKEY = S_SUPPKEY JOIN
  (SELECT C_CUSTKEY, C_REGION FROM customer WHERE C_REGION = 'AMERICA') as customer ON LO_CUSTKEY = C_CUSTKEY
GROUP BY EXTRACT(YEAR FROM LO_ORDERDATE), S_NATION, P_CATEGORY
ORDER BY EXTRACT(YEAR FROM LO_ORDERDATE) ASC, S_NATION ASC, P_CATEGORY ASC;
 
-- Q4.3
SELECT EXTRACT(YEAR FROM LO_ORDERDATE), S_CITY, P_BRAND, sum(LO_REVENUE - LO_SUPPLYCOST) AS profit
FROM(SELECT LO_ORDERDATE, LO_REVENUE, LO_CUSTKEY, LO_SUPPKEY, LO_PARTKEY, LO_SUPPLYCOST FROM lineorder
   WHERE LO_ORDERDATE >= DATE '1997-01-01' AND LO_ORDERDATE < DATE '1999-01-01') as lineorder JOIN
  (SELECT P_PARTKEY, P_BRAND FROM part WHERE P_CATEGORY = 'MFGR#14') ON LO_PARTKEY = P_PARTKEY JOIN
  (SELECT S_SUPPKEY, S_NATION, S_CITY FROM supplier WHERE S_NATION = 'UNITED STATES') ON LO_SUPPKEY = S_SUPPKEY JOIN
  customer ON LO_CUSTKEY = C_CUSTKEY
GROUP BY EXTRACT(YEAR FROM LO_ORDERDATE), S_CITY, P_BRAND
ORDER BY EXTRACT(YEAR FROM LO_ORDERDATE) ASC, S_CITY ASC, P_BRAND ASC;